### ISSUE TITLE
Miss the JSON files in the downloaded datasets.

### ISSUE THREAD

**Issue by zhouyangming** [THU-BPM/MR2#1]
The full JSON files are not provided in the project.

**Comment by plw-study** [comment]
It seems that the problem has not been solved. I had the same problem. Did you get the complete json files?

**Comment by chenjz20Thu** [comment]
We have uploaded the relevant json file in https://drive.google.com/file/d/14NNqLKSW1FzLGuGkqwlzyIPXnKDzEFX4/view?usp=sharing .
