### ISSUE TITLE
Miss the claim sentences of the source posts in the downloaded dataset. 

### ISSUE THREAD

**Issue by plw-study** [THU-BPM/MR2#3]
Miss the claim sentences of the source posts (only the images and searching results).  The train/test/val split of the dataset is missing.

**Comment by chenjz20Thu** [comment]
We have uploaded the relevant json file in https://drive.google.com/file/d/14NNqLKSW1FzLGuGkqwlzyIPXnKDzEFX4/view?usp=sharing .
